### PR TITLE
Tweak union's encoding

### PR DESCRIPTION
**Pull request by daddykotex**
Related to #82, but different.

Depends on https://github.com/disneystreaming/alloy/pull/59

### CODE REVIEW

**Comment by Baccata** [comment]
It may have not been caught in previous reviews, but I'd like to see a test with the inline trait where custom proto indexes are used on union members.

**Comment by daddykotex** [comment]
> It may have not been caught in previous reviews, but I'd like to see a test with the inline trait where custom proto indexes are used on union members.

I'll make sure it's there. I think it is because the `protoIndex` requires every field to be annotated and I would believe this extends to the union in that case, but I'll confirm

**Comment by daddykotex** [comment]
> It may have not been caught in previous reviews, but I'd like to see a test with the inline trait where custom proto indexes are used on union members.

Good catch, there is a potential issue

**Comment by daddykotex** [comment]
Fixed the validator and introduced a few use cases to address this: https://github.com/disneystreaming/alloy/pull/60

**Review by Baccata — APPROVED** [review]
👍

**Pull request merged**
